@startuml
'https://plantuml.com/class-diagram

interface Subject {
    + registerObserver(o: Observer)
    + removeObserver(o: Observer)
    + notifyObservers()
}

interface Observer {
    + update(data: DataType)
}

class ConcreteObserver {
    - subject : Subject
    + ConcreteObserver(subject: Subject)
    + update(data: DataType)
}

class ConcreteSubject implements Subject {
    - observers : List<Observer>
    - data : DataType
    + ConcreteSubject()
    + registerObserver(o: Observer)
    + removeObserver(o: Observer)
    + notifyObservers()
    + setData(newData: DataType)
}

ConcreteObserver --|> Observer
ConcreteObserver --> ConcreteSubject
Subject -right-> Observer : notifies


@enduml