@startuml
'https://plantuml.com/class-diagram

class Singleton {
    - static instance : Singleton
    - Singleton()
    + static getInstance() : Singleton
}

note right of Singleton::getInstance
  This is a static method
  that returns the single
  instance of this class.
end note

Singleton .. Singleton: << creates >>

@enduml